### ISSUE TITLE
Cannot run plain espresso tests with custom CucumberAndroidJUnitRunner in Java

### ISSUE THREAD

**Issue by IgnacioGarcia198** [cucumber/cucumber-android#101]
### 👓 What did you see?
I made a test project with both Cucumber and plain Espresso tests, using a custom runner extending CucumberAndroidJUnitRunner. 
I tested it with files in Kotlin and worked.
I tested it again with files in Java and, when I try to run my plain Espresso test, my Cucumber test is launched instead, every single time. 

### ✅ What did you expect to see?
I expected that both Cucumber and plain Espresso tests would work in Java, same as in Kotlin.

### 📦 Which tool/library version are you using?
```
androidTestImplementation 'io.cucumber:cucumber-android:4.8.3'
androidTestImplementation 'io.cucumber:cucumber-picocontainer:4.8.1'
```

### 🔬 How could we reproduce it?
Reproduce it using this test [project](https://github.com/IgnacioGarcia198/EspressoCucumberTest).
Last commit in main branch is in Java and failing, if you just checkout previous commit it is in Kotlin and both tests work.

1. Open project
2. Run test MainActivitySteps and verify it's passing
3. Run test ExampleInstrumentedTest and verify MainActivitySteps is running instead
4. Checkout commit "both tests working in Kotlin" 48735819
5. Run test MainActivitySteps and verify it's passing
6. Run test ExampleInstrumentedTest and verify it actually runs and passes
7. EDIT: It is not working now on Kotlin either

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by lsuski** [comment]
To run plain tests you have to execute tests with instrumentation argument `cucumberUseAndroidJUnitRunner=true`
