### ISSUE TITLE
cucumber integration reporting package

### ISSUE THREAD

**Issue by stanroy** [cucumber/cucumber-android#105]
### 🤔 What's the problem you're trying to solve?

When using [Marathon](https://github.com/MarathonLabs/marathon) with Cucumber I'm facing a problem where log and HTML files are generated with a leading dot. I was told that cucumber tests do not report any package and that's why I'm having this problem.

### ✨ What's your proposed solution?

For cucumber integration to report some package if it's possible

### ⛏ Have you considered any alternatives or workarounds?

Would probably have to make some workaround on the marathon side

Link to the issue in Marathon repo
https://github.com/MarathonLabs/marathon/issues/689

**Comment by lsuski** [comment]
Hi, so of I correctly understand there should be a package added when reporting test case. I'll look into it but any PR could speed up this process

**Comment by lsuski** [comment]
Fixed in https://github.com/MarathonLabs/marathon/issues/689
