### ISSUE TITLE
issue canot run test example 

### ISSUE THREAD

**Issue by vudangalax** [cucumber/cucumber-android#11]
Testing started at 5:19 PM ...

10/10 17:19:43: Launching Cucumber
$ adb push /Users/apple/Downloads/cucumber-android-master/cukeulator/build/outputs/apk/debug/cukeulator-debug.apk /data/local/tmp/cucumber.cukeulator
$ adb shell pm install -t -r "/data/local/tmp/cucumber.cukeulator"
Success
APK installed in 7 s 871 ms
$ adb push /Users/apple/Downloads/cucumber-android-master/cukeulator/build/outputs/apk/androidTest/debug/cukeulator-debug-androidTest.apk /data/local/tmp/cucumber.cukeulator.test
$ adb shell pm install -t -r "/data/local/tmp/cucumber.cukeulator.test"
Success
APK installed in 9 s 451 ms
Running tests

$ adb shell am instrument -w -r   -e debug false cucumber.cukeulator.test/cucumber.cukeulator.test.CucumberRunner
Client not ready yet..
Started running tests
Test running failed: Instrumentation run failed due to 'Process crashed.'
Empty test suite.

**Comment by lsuski** [comment]
app crashes because of this https://github.com/cucumber/cucumber/issues/494
