### ISSUE TITLE
Running tests from feature files directly in android studio fails

### ISSUE THREAD

**Issue by renetik** [cucumber/cucumber-android#110]
When I download this repository and open in android studio, I build project and everything looks fine, then I go to feature file and click on arrow to run individual test. It fails ! 

Is this not supported at all ? Is there some feature request or bug report for this already ? 

<img width="776" alt="Screenshot 2023-02-08 at 16 39 25" src="https://user-images.githubusercontent.com/923610/217577418-01f70b3c-796b-4e87-a00c-519933b58e9d.png">

<img width="1198" alt="Screenshot 2023-02-08 at 16 39 55" src="https://user-images.githubusercontent.com/923610/217577542-09aba136-06b2-4e7f-926c-4208038952c8.png">

It fails here:
java.lang.IllegalStateException: No instrumentation registered! Must run under a registering instrumentation.
	at androidx.test.platform.app.InstrumentationRegistry.getInstrumentation(InstrumentationRegistry.java:45)
	at androidx.test.core.app.ApplicationProvider.getApplicationContext(ApplicationProvider.java:41)
	at dagger.hilt.android.internal.testing.MarkThatRulesRanRule.<init>(MarkThatRulesRanRule.java:43)
	at dagger.hilt.android.testing.HiltAndroidRule.<init>(HiltAndroidRule.java:36)

But you can just test it out easily on your own repo so I believe you already know this and it is not implemented nor planned ? 
Why ?

PS: I  see and know that I can run tests but other means. This question is about this specific way of running tests and why it is not supported nor reported as not working somewhere. Thanks.

**Comment by lsuski** [comment]
You can try this plugin now https://plugins.jetbrains.com/plugin/22107-cucumber-for-kotlin-and-android
