### ISSUE TITLE
Cucumber with Hilt No tests found

### ISSUE THREAD

**Issue by Jeasmine** [cucumber/cucumber-android#113]
### 👓 What did you see?

com.android.build.gradle.internal.testing.ConnectedDevice > No tests found.[SM-G998B - 13] FAILED 
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).

### 📦 Which tool/library version are you using?

androidTestImplementation "io.cucumber:cucumber-android:4.10.0"
androidTestImplementation "io.cucumber:cucumber-android-hilt:4.10.0"

### 📚 Any additional context?

I'm able to run cucumber android cukeulator example. On my current android project if I don't add the android hilt dependency, the cucumber test are running with no problem. When I add the cucumber-android-hilt I also need to add the newApplication method

```
@CucumberOptions(
    features = ["features"],
    strict = true
)
class CucumberTestRunner : CucumberAndroidJUnitRunner() {

    @Throws(
        ClassNotFoundException::class,
        IllegalAccessException::class,
        InstantiationException::class
    )
    override fun newApplication(
        cl: ClassLoader?,
        className: String?,
        context: Context?
    ): Application? {
        return super.newApplication(cl, CustomHiltApp_Application::class.java.name, context)
    }

}
```

```
@CustomTestApplication(ZeroApp::class)
interface CustomHiltApp {
}
```

I needed to create my own CustomTestApplication since ZeroApp (being the Android Application class) has some EntryPoint that I need in the onCreate method. The project is using hilt, retrofit, room and coroutines as main dependencies.

The problem is that before adding the cucumber hilt dependency the cucumbers tests run correctly, after I add the hilt dependency tests stop being recognized, even If I add the @HiltAndroidTest annotation.

I can't share my current project but will try to make one with the error.  But in the mean time I want to know if this is something that somebody has experience before or has some clue about it. Thanks

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by lsuski** [comment]
Any logs from logcat?
