### ISSUE TITLE
Not able to use annotations to create type definitions

### ISSUE THREAD

**Issue by dzielins42** [cucumber/cucumber-android#114]
### 👓 What did you see?

`Unresolved reference: ParameterType`

### ✅ What did you expect to see?

I would like to be able to use `@ParameterType` annotation to define custom type. Currently I have to use `TypeRegistryConfigurer`. 

### 📦 Which tool/library version are you using?

`cucumber-android` 4.10.0

### 🔬 How could we reproduce it?

```
package com.example

import io.cucumber.java.ParameterType
import io.cucumber.java.en.Given

data class Book(
  val bookName: String,
)

class StepDefinitions {

  @ParameterType(".*")
  fun book(bookName: String): Book {
    return Book(bookName)
  }

  @Given("{book} is my favorite book")
  fun this_is_my_favorite_book(book: Book) {
    // step implementation
  }
}
```

Above example is from https://cucumber.io/docs/cucumber/configuration/?lang=kotlin

### 📚 Any additional context?

Issue is probably caused by outdated dependency. `cucumber-android` 4.10.0 depends on `cucumber-java` 4.8.1. It does not have `ParameterType`. When I manually add newer version dependency in `build.gradle`, it causes runtime errors (`java.lang.NoClassDefFoundError: Failed resolution of: Lcucumber/runtime/ClassFinder`). Dependency update is required in `cucumber-android`.

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by lsuski** [comment]
Fixed in `7.14.0`
