### ISSUE TITLE
Run tests in isolation without code changes

### ISSUE THREAD

**Issue by tassilo-posegga** [cucumber/cucumber-android#117]
Hi there!

I am trying to figure out how to run tests in isolation / not running all Cucumber tests at once. I don't want to change the `CucumberOptions` in code and I am looking for an easy way to do that. I want to only run the test I am currently working on.

The most amazing solution would be using the [Cucumber+](https://plugins.jetbrains.com/plugin/16289-cucumber-) plugin from within Android Studio. 
I could also deal with a gradle task taking the arguments for feature files or senario names or tags.
Is there something I did overlook?

**Comment by lsuski** [comment]
Try in @CucumberOptions features="path/to/feature/feature_file.feature:15" where 15 is line number where scenario starts

**Comment by tassilo-posegga** [comment]
Sorry, I think hadn't make that clear - I am looking for a way which wouldn't require any code changes.

**Comment by lsuski** [comment]
I have written Android Studio plugin for that purpose and I'm going to open source it in next week

**Comment by tassilo-posegga** [comment]
Looking very much forward to this!

**Comment by lsuski** [comment]
Check this plugin https://plugins.jetbrains.com/plugin/22107-cucumber-for-kotlin-and-android
