### ISSUE TITLE
Automatically deploy release artifacts

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-android#12]
Snapshot artifacts are automatically released. Release artifacts have to be released using the [gradle-nexus-staging-plugin](https://github.com/Codearte/gradle-nexus-staging-plugin/)

As cucumber v4 has been released I think we should revisit the release process.

**Comment by lsuski** [comment]
I closed cucumber-android 4.0.0 but it didn't show up in jcenter or maven central. As I understand this requires some manual work and `gradle-nexus-staging-plugin` automates it.

**Comment by lsuski** [comment]
@mpkorstanje could you release cucumber-android manually from Nexus GUI? I pushed 4.0.0 (https://travis-ci.org/cucumber/cucumber-android/builds/440590566) so the artifacts should be available, but I don't have access rights for further steps

**Comment by mpkorstanje** [comment]
Done.

**Comment by lsuski** [comment]
There should be aar. @mpkorstanje could you check if cucumber-android-4.0.0.aar was published?

**Comment by mpkorstanje** [comment]
That is odd. I would expect the release to work the same as it does for snapshots. I can't see what happened in nexus any more.

**Comment by mpkorstanje** [comment]
So the weird thing is. All artifacts uploaded to nexus. But there are four different staging repositories. Each with a few of the required files. Seems there is a load balancer between the build server and nexus.

https://issues.sonatype.org/browse/OSSRH-19485

**Comment by lsuski** [comment]
@mpkorstanje I've added plugin configuration, could you check if this works?

**Comment by mpkorstanje** [comment]
A few problems.

1. The build fails for snapshots because there is no repository to close.
2. The plugin you've added only manages staging repositories. It doesn't handle uploading so it won't solve the problems caused by being behind a load balancer.

**Comment by lsuski** [comment]
So, 
1. there need to be some conditional step invoking closing repository only for closed versions
2. according to workaround mentioned in issue specifying `stagingProfileId` should fix it, however I don't know what value ith should be, how this is solved in cucumber-jvm because it does not look like gradle only issue?

**Comment by mpkorstanje** [comment]
1. Yes. Maybe some shell scripting is needed here.

2. Yes. When uploading. But the gradle maven deploy plugin doesn't seem to
support that. It just uploads everything.

**Comment by lsuski** [comment]
I've setup https://github.com/marcphilipp/nexus-publish-plugin but build failed because of timeout. Currently build fails twice because of `java.io.IOException: No space left on device`. I'm not sure but maybe there need to be done some manual cleaning on Nexus

**Comment by mpkorstanje** [comment]
Can't image that we fix that. It's Sonatypes Nexus, not ouds. I've restarted the build. let's see.

**Comment by mpkorstanje** [comment]
Can't image that we fix that. It's Sonatypes Nexus, not ouds. I've restarted the build. let's see.

**Comment by lsuski** [comment]
Nice, deploy succeeded but the pom does not contain dependencies. I need to fix that

**Comment by lsuski** [comment]
Ok, version 4.1.2 released with correct pom

**Comment by mpkorstanje** [comment]
Awesome! Nicely done.
