### ISSUE TITLE
Support for Loading .feature Files from Emulator Private Data Storage in cucumber-android

### ISSUE THREAD

**Issue by neelam-kushwah** [cucumber/cucumber-android#123]
I want to utilize .feature files from the private data storage path on my emulator. Despite using 'am instrument -e features [path.to.file]', it appears that cucumber-android expects the files to be in resources rather than the file system. I'm inquiring about the feasibility of this with the current implementation.

**Comment by lsuski** [comment]
Yes, current implementation expects features to be in assets. However it shouldn't be much complicated to extend this behaviour. It's probably a matter of adding another `Resource` implementation in `AndroidFeatureSupplier`

**Comment by neelam-kushwah** [comment]
Thanks for your response @lsuski . I have implemented the necessary changes in the AndroidFeatureSupplier for the solution. It is now working fine, and I am closing the issue accordingly.

**Comment by lsuski** [comment]
Do you implemented it in your fork? Can you create PR?
