### ISSUE TITLE
Scenario/Scenario Outline with / causes all tests to not run with no useful indication of why

### ISSUE THREAD

**Issue by johngray1965** [cucumber/cucumber-android#129]
### 👓 What did you see?

Setting up a new test set resulted in all of the tests to fail.  They don't actually run.   The cause turned to be a new tests with named "Show Previous/Next Doc".  The issue was the /.   There was no useful error indicating the problem was in illegal character in the title in either logcat or the console. 

### ✅ What did you expect to see?

If the test with the slash was in set of tests I tried to run, 0 tests were executed.  If I ran tests that didn't include the test with the slash, everything was fine.  

on the device I see the following error:
                         E  androidx.test.internal.events.client.TestEventClientException: Unable to add test, Orchestrator callback is null
                         E      at androidx.test.orchestrator.callback.OrchestratorV1Connection.send(OrchestratorV1Connection.java:79)
                         E      at androidx.test.internal.events.client.TestDiscoveryListener.testRunFinished(TestDiscoveryListener.java:71)
                         E      at org.junit.runner.notification.SynchronizedRunListener.testRunFinished(SynchronizedRunListener.java:42)
                         E      at org.junit.runner.notification.RunNotifier$2.notifyListener(RunNotifier.java:103)
                         E      at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
                         E      at org.junit.runner.notification.RunNotifier.fireTestRunFinished(RunNotifier.java:100)
                         E      at org.junit.runner.JUnitCore.run(JUnitCore.java:138)
                         E      at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
                         E      at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:67)
                         E      at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:58)
                         E      at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:446)
                         E      at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2248)

Which certainly doesn't give any helpful indication of the actual problem.  I believe the Orchestrator callback is null because didn't set up any test successfully.

BTW, I'm fine with / not be allowed, but I won't nice if:

1. It didn't cause other tests to not run
2. It gave some meaningful indication of what the problem was.  It was quite a time suck figuring out it was slash in the feature title.

### 📦 Which tool/library version are you using?

io.cucumber:cucumber-android:7.14.0
io.cucumber:cucumber-android-hilt:7.14.0

### 🔬 How could we reproduce it?

The test in question used hilt, but I suspect it doesn't matter.   This is test that caused the issue:
  @TEST_RD-812 @TESTSET_RD-811
  Scenario Outline: Show Previous/Next Doc
    Given showPrevNextDoc is <showPrevNextDoc>
    And I have a ControlSettingsScreen
    And verify showPrevNextDoc switch is <showPrevNextDoc>
    And I flip the showPrevNextDoc switch from <showPrevNextDoc> to <alt>
    And verify showPrevNextDoc switch is <alt>
    And verify showPrevNextDoc setting is <alt>
    Examples:
      | showPrevNextDoc | alt |
      | true | false |
      | false | true |

BTW, doesn't matter how the steps are implemented, they can be empty.

**Comment by johngray1965** [comment]
This was a problem with testing Compose.  The ComposeRuleHolder needs to be in the glue folder:
@CucumberOptions(
        features = "features",
        glue = "my.package.test.steps"
)
The docs says something about this, but doesn't writing very well.   I figured this out after finding comment on issue here that said the ComposeRuleHolder needed to be in the glue package.   Please fix the docs so it says very directly that the location of ComposeRuleHolder must be one the glue packages.  It could me way longer than it should to fix that very simple issue.

**Comment by lsuski** [comment]
I've enhanced README in latest main, thanks
