### ISSUE TITLE
StringIndexOutOfBoundsException occurs when there is no dot in the class package.

### ISSUE THREAD

**Issue by carter-rs** [cucumber/cucumber-android#131]
### 👓 What did you see?

When running tests in the KMP project, a StringIndexOutOfBoundsException occurs in the internal package inspection logic. As shown in the attached snapshot, there are cases where a string without a dot is passed.

07-24 13:35:43.010 14550 14654 E TestRunner: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 12
07-24 13:35:43.010 14550 14654 E TestRunner: 	at java.lang.String.checkBoundsBeginEnd(String.java:4466)
07-24 13:35:43.010 14550 14654 E TestRunner: 	at java.lang.String.substring(String.java:2517)
07-24 13:35:43.010 14550 14654 E TestRunner: 	at io.cucumber.android.CucumberJunitRunner$getCucumberOptionsClass$1.invoke(CucumberJunitRunner.kt:131)
07-24 13:35:43.010 14550 14654 E TestRunner: 	at io.cucumber.android.CucumberJunitRunner$getCucumberOptionsClass$1.invoke(CucumberJunitRunner.kt:130)

<img width="1402" alt="스크린샷 2024-07-24 오후 1 35 25" src="https://github.com/user-attachments/assets/a4344775-fb1c-4217-a739-a93b6a61e8b2">

### ✅ What did you expect to see?

KMP project testing

### 📦 Which tool/library version are you using?

io.cucumber:cucumber-android:7.14.0

### 🔬 How could we reproduce it?

Reproduce after setting up and running the Android module of the KMP project.

**Comment by carter-rs** [comment]
@lsuski Why was the issue closed?

**Comment by mpkorstanje** [comment]
It is explained in the timeline:

![image](https://github.com/user-attachments/assets/17da1500-1356-4369-8811-936b674fd27c)
