### ISSUE TITLE
Doesn't exist 7.14.1 on mvn? 

### ISSUE THREAD

**Issue by enciyo** [cucumber/cucumber-android#138]
### 👓 What did you see?

I don't see 7.14.1 version on Maven. Can you check this on https://mvnrepository.com/artifact/io.cucumber/cucumber-android

### ✅ What did you expect to see?

I will except to v7.14.1

### 📦 Which tool/library version are you using?

cucember-android v7.14.1

**Comment by lsuski** [comment]
It's actually [7.18.1](https://mvnrepository.com/artifact/io.cucumber/cucumber-android/7.18.1) - there were some issues with releasing version last time and release notes are wrong

**Comment by mpkorstanje** [comment]
@lsuski do you have enough permissions to edit the releases at https://github.com/cucumber/cucumber-android/releases?

**Comment by lsuski** [comment]
Yes, I updated it
