### ISSUE TITLE
cucumber-android does not integrate very well with Android Orchestrator

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-android#2]
_From @mariusbob on February 15, 2018 9:54_

I have just added android orchestrator in my project and it seems that the tests are running, the reports are generated, but I get this error:
```
com.android.builder.testing.ConnectedDevice > No tests found.[Moto G (4) - 7.0] FAILED 
No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations).
```

As I know, orchestrator takes every test method(annotated with @Test, obviously) and executes it in a separate process. Is it really a problem for cucumber-android?

_Copied from original issue: cucumber/cucumber-jvm#1324_

**Comment by aslakhellesoy** [comment]
_From @brasmusson on February 18, 2018 19:43_

Cucumber-JVM executes Pickles compiled from Scenarios in Feature files, not methods annotated with `@Test`. If the Android Orchestrator searches for methods annotated with `@Test`, I'm not surpriced it reports "No tests found". Were do you expect it to find methods annotated with `@Test`?

**Comment by aslakhellesoy** [comment]
_From @mariusbob on February 20, 2018 13:52_

You're right, I don't have methods annotated with `@Test`, but the thing is that the tests are executed, reports are generated but the error on console is "No tests found."

**Comment by aslakhellesoy** [comment]
_From @brasmusson on February 20, 2018 19:29_

> the thing is that the tests are executed, reports are generated but the error on console is "No tests found."

So?? You have both cucumber-android and Android Orchestrator in your projekt (and no `@Test` methods). Cucumber-android executes its test (not relying on any `@Test` methods), at the same time Android Orchestrator searches for `@Test` methods, finds none, and says exactly that on the console. I do not see that cucumber-android can to anything about Android Orchestrator reporting that it did not find any `@Test` methods. 

I do not understand why you added Android Orchestrator to your project when you have no `@Test` methods, which is what Android Orchestrator searches for and executes.

I thinks this issue should be closed, but feel free to provide a pull request if you see any possibility that cucumber-android and Android Orchestrator can be integrated in any way.

**Comment by aslakhellesoy** [comment]
_From @nbransby on April 16, 2018 15:34_

I had to create a testInstrumentationRunner (replacement for android.support.test.runner.AndroidJUnitRunner) and a org.junit.runner.Runner (replacement for cucumber.api.junit.Cucumber) that combines cucumber-android and cucumber-junit to run scenerios isolated in seperate processes via orchestrator.

**Comment by aslakhellesoy** [comment]
_From @bandyguy on June 1, 2018 13:21_

@nbransby Is there any way you could provide more details / an example of how you got this working? I have observed the same scenario. It would be nice to achieve isolation in tests that the Android Orchestrator attempts to provide.

**Comment by aslakhellesoy** [comment]
_From @nbransby on June 2, 2018 10:3_

@bandyguy I started by making a copy of the source of the two classes I replaced then changed the relevant parts

 I've added my work to a gist here: https://gist.github.com/nbransby/24013c6b335a085c0d875244bcefb70e

**Comment by petrsvobodnikspider** [comment]
Hi, any chance it will be fixed? Solution about does not work for me as I get an exception:  cucumber.runtime.CucumberException: Failed to instantiate class xxxx

Seems to be related to old version of cucumber library.

**Comment by lifedemons** [comment]
Hi everybody, I've been looking for some time how to solve this issue and opened corresponding PR: https://github.com/cucumber/cucumber-android/pull/14 
So, it doesn't work with all features of Android Test Orchestrator(let's filtering of tests by Test Class name will not work for Cucumber non-Class tests), but it supports tests sharding and dynamic Spoon test sharding.
Please, look and give your opinions. @aslakhellesoy @lsuski

**Comment by lsuski** [comment]
This should work now due to https://github.com/cucumber/cucumber-android/pull/14
