### ISSUE TITLE
CucumberAndroidJUnitRunner isn't a test class

### ISSUE THREAD

**Issue by shickadam** [cucumber/cucumber-android#20]
I am unable to get cucumber running through android studio now with the androidx upgrade. I am using the same Runner as in cukelator. Mine is written in kotlin:  

import android.os.Bundle
import cucumber.api.CucumberOptions
import cucumber.api.android.CucumberAndroidJUnitRunner
import java.io.File

@CucumberOptions(features = ["features"], tags=["~@WIP"]])
class CucumberRunner : CucumberAndroidJUnitRunner() {

  override fun onCreate(bundle: Bundle) {
    bundle.putString("plugin", getPluginConfigurationString()) // we programmatically create the plugin configuration
    super.onCreate(bundle)
  }

  /**
   * Since we want to checkout the external storage directory programmatically, we create the plugin configuration
   * here, instead of the [CucumberOptions] annotation.
   *
   * @return the plugin string for the configuration, which contains XML, HTML and JSON paths
   */
  private fun getPluginConfigurationString(): String {
    val cucumber = "cucumber"
    val separator = "--"
    return "junit:${getAbsoluteFilesPath()}/$cucumber.xml${separator}html:${getAbsoluteFilesPath()}/" +
        "$cucumber.html${separator}json:${getAbsoluteFilesPath()}/$cucumber.json"
  }

  /**
   * The path which is used for the report files.
   *
   * @return the absolute path for the report files
   */
  private fun getAbsoluteFilesPath(): String {
    // Since stupidly, connected-check tasks uninstall the applications,
    // we have to find a directory outside the application directory.
    val directory = targetContext.getExternalFilesDir(null)
    return File(directory, "reports").absolutePath
  }
}

**Comment by shickadam** [comment]
Fixed it by adding 
@Test
  fun whatever() {}

 Inside the runner

**Comment by lsuski** [comment]
It should not be necessary. I think that you run tests incorrectly. You should add run configuration for all tests in module.
