### ISSUE TITLE
issue of running sh cmd with pipe

### ISSUE THREAD

**Issue by kyrie2014** [cucumber/cucumber-android#24]
it only execute the first cmd when to run sh cmd with pipe.

example:
device.executeShellCommand("ls | grep xxxx"),  cmd "ls" can run successfully, but "grep xxx" not

**Comment by lsuski** [comment]
How does it relate to cucumber-android?

**Comment by kyrie2014** [comment]
Normal circumstances is pass without cucumber, but happened in cucumber-android.

**Comment by lsuski** [comment]
Information you provided does not relate in any way with cucumber. You need to first extract  error and then come back here. Running some shell script is not part of cucumber-android.
