### ISSUE TITLE
java.lang.SecurityException: Calling from not trusted UID!

### ISSUE THREAD

**Issue by Kavish1408** [cucumber/cucumber-android#25]
I am getting crash with message "java.lang.SecurityException: Calling from not trusted UID!" while running with following command at the end of test execution.
"gradle connectedAndroidTest -Ptags="@tagname""

I am working on BDD automation with the following project structure.

androidTest -> assets
                        java

In "assets" folder we have feature file and Golden Images.
In  "java" folder we have Stepdefintion files.
And One Instrumentation Class with below structure

@CucumberOptions(features = "features", glue = "com.android.automation")
public class Instrumentation extends MonitoringInstrumentation { 

}

**Comment by lsuski** [comment]
@Kavish1408 Please provide full stacktrace

**Comment by Kavish1408** [comment]
E/com..android.vip.util.CustomUncaughtExceptionHandler(12897): Activity crashed: com.android.cardmanager.MainActivity
E/com.android.vip.util.CustomUncaughtExceptionHandler(12897): Unknown activity crashed: com.cardmanager.MainActivity
E/com.android.vip.util.CustomUncaughtExceptionHandler(12897): com.android.vip crashed. java.lang.SecurityException: Calling from not trusted UID!
E/com.android.vip.util.CustomUncaughtExceptionHandler(12897): 	at android.os.Parcel.readException(Parcel.java:1431) ~[na:0.0]
E/com.android.vip.util.CustomUncaughtExceptionHandler(12897): 	at android.os.Parcel.readException(Parcel.java:1385) ~[na:0.0]
E/com.android.vip.util.CustomUncaughtExceptionHandler(12897): 	at android.app.ActivityManagerProxy.finishInstrumentation(ActivityManagerNative.java:2954) ~[na:0.0]
E/com.android.vip.util.CustomUncaughtExceptionHandler(12897): 	at android.app.ActivityThread.finishInstrumentation(ActivityThread.java:4466) ~[na:0.0]
E/com.android.vip.util.CustomUncaughtExceptionHandler(12897): 	at android.app.Instrumentation.finish(Instrumentation.java:196) ~[na:0.0]
E/com.android.vip.util.CustomUncaughtExceptionHandler(12897): 	at android.support.test.runner.MonitoringInstrumentation.finish(MonitoringInstrumentation.java:351) ~[na:0.0]
E/com.android.vip.util.CustomUncaughtExceptionHandler(12897): 	at cucumber.api.android.CucumberInstrumentationCore.start(CucumberInstrumentationCore.java:92) ~[na:0.0]
E/com.android.vip.util.CustomUncaughtExceptionHandler(12897): 	at com.android.vip.service.Instrumentation.onStart(Instrumentation.java:38) ~[na:0.0]
E/com.android.vip.util.CustomUncaughtExceptionHandler(12897): 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701) ~[na:0.0]
W/System.err(12897): java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)
W/System.err(12897): 	at libcore.io.IoBridge.open(IoBridge.java:409)
W/System.err(12897): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:88)
W/System.err(12897): 	at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.openFile(FileOutput.java:67)
W/System.err(12897): 	at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.writeExecutionData(FileOutput.java:53)
W/System.err(12897): 	at org.jacoco.agent.rt.internal_8ff85ea.Agent.shutdown(Agent.java:137)
W/System.err(12897): 	at org.jacoco.agent.rt.internal_8ff85ea.Agent$1.run(Agent.java:54)
W/System.err(12897): Caused by: libcore.io.ErrnoException: open failed: EROFS (Read-only file system)
W/System.err(12897): 	at libcore.io.Posix.open(Native Method)
W/System.err(12897): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
W/System.err(12897): 	at libcore.io.IoBridge.open(IoBridge.java:393)
W/System.err(12897): 	... 5 more
I/AndroidRuntime(12897): VM exiting with result code 0, cleanup skipped.
W/ResourceType( 2794): No package identifier when getting value for resource number 0x00000000
W/ResourceType( 2794): No package identifier when getting value for resource number 0x00000000
I/ActivityManager( 1637): Process com.android.vip (pid 12897) has died.
W/ActivityManager( 1637): Crash of app com.android.vip running instrumentation ComponentInfo{com.android.vip.service/com.android.vip.service.Instrumentation}

**Comment by lsuski** [comment]
I don't see cucumber in this stacktrace, disable testCoverage and check again. Stacktrace suggests that there is some issue with jacoco

**Comment by lsuski** [comment]
Either it is `Activity crashed: com.android.cardmanager.MainActivity` or jacoco. `CucumberInstrumentationCore` is just instrumentation so many stacktraces will have it

**Comment by Kavish1408** [comment]
Yes, While running our tests with the command line (gradle connectedAndroidTest -Ptags="@tagname") it is working fine but after execution of the last scenario Activity is getting crashed. with the message that cardmanager has stopped.

**Comment by lsuski** [comment]
So, as I said this is probably bug in your activity, you can check cucumber 4.3.0 also if this happens

**Comment by Kavish1408** [comment]
androidTestImplementation 'com.android.support.test:rules:1.0.2'
   androidTestImplementation 'com.android.support.test:runner:1.0.2'
   androidTestImplementation 'com.android.support.test.uiautomator:uiautomator-v18:2.1.3'
   androidTestImplementation 'info.cukes:cucumber-picocontainer:1.2.4'
   androidTestImplementation 'com.android.support.test:rules:1.0.2'
   androidTestImplementation 'info.cukes:cucumber-android:1.2.4@jar'

these are the dependencies which we have added in our .gradle file

**Comment by lsuski** [comment]
So I suggests you to migrate to cucumber 4.3.0.

**Comment by Kavish1408** [comment]
ok thanks once i will try what u suggested and revert u back if u don't mind :-)
