### ISSUE TITLE
Reports are getting deleted before the gradle tasks can pull the reports.

### ISSUE THREAD

**Issue by vinuthareddy** [cucumber/cucumber-android#27]
i am running cucumber tests in android and trying to store the report in the externalDirectory which seems to be "/storage/emulated/0/Android/data//files". During the test execution i can see the reports getting generated. But the reports are deleted when the app gets un-installed. 
Can anyone please help me copy the reports to the desktop before they get deleted.

i have tried to store the reports in a couple of other locations such as "/sdcard", "/mnt/sdcard" , "/storage/emulated/0" . I haven't had luck with any of these. i get IOException. seems i don't have permissions to write to these locations.

**Comment by lsuski** [comment]
Check cukeulator sample. There are reports generated. You can also use spoon gradle plugin. The problem with connectedDebugAndroidTest is that it uninstalls application after tests and all app data are deleted. You can also use gradle report generated by this task which is quite readable in my opinion

**Comment by vinuthareddy** [comment]
Here is a more detailed explanation : 
i have exactly followed the steps mentioned in cukeulator example.

step 1 : "./gradlew --parallel :app:assembleAndroidTest" to generate a test apk.
step 2 : installed the apk on the emulator.
step 3 : "adb shell pm list instrumentation"
it displays the cucumber testRunner.

When i run "./gradlew connectedCheck"  connectedDebugAndroidTest is executed successfully but the reports are deleted when the app gets un-installed like you have mentioned above.

when i run "./gradlew spoon"  spoonDebugAndroidTest is executed and i am getting the following error.

Execution failed for task ':rei:spoonDebugAndroidTest'.
> Test APK path does not exist.

**Comment by lsuski** [comment]
Strange. I use spoon for all my projects and simple gradlew spoondDebugAndroidTest works fine. You can share sample project which reproduces issue
