### ISSUE TITLE
Reported duration time of scenario is about 0ms on Android 

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-android#3]
_From @lsuski on July 5, 2018 18:7_

Hi, 
I've recently build locally cucumber 4.0.0-SNAPSHOT and tried it on Android and encounter issue with scenario duration time. For most of scenarios it is about 0ms or 25ms or 75ms so generally it is very short but test takes naturally longer. With Cucumber 2.4.0 execution time is normal (average 2s per scenario). I was digging whole day  in code base but could not find any reason for that.
Was there any change between 2.4.0 and 4.0.0-SNAPSHOT which could introduce such issue on Android?

_Copied from original issue: cucumber/cucumber-jvm#1413_

**Comment by aslakhellesoy** [comment]
_From @mpkorstanje on July 5, 2018 18:32_

If you can tell me where the time is reported I might be able to help.

**Comment by lsuski** [comment]
I mean the time shown in Android Studio test execution tab on the right of scenario name

**Comment by mpkorstanje** [comment]
Sure. But where does that time come from?

**Comment by mpkorstanje** [comment]
We did stop using XStream in 3.x for our transformations. That might have something to do with it, XStream involved quite a bit of class path scanning.

**Comment by mpkorstanje** [comment]
Does it add up wit the reported durations in logcat?

**Comment by lsuski** [comment]
I'll check tomorrow, but execution time is slower than reported, it takes about 2 s per scenario but reported in Android Studio is 0ms. I have no idea where does that time come from. I thought it is reported to Instrumentation but it is not and it wasn't as well in 2.4.0. The only place where duration from `Result` is taken into account is `Stats`

**Comment by lsuski** [comment]
There is `cucumber.api.event.TestCaseFinished` class which holds `cucumber.api.Result` with duration. But I can't find a place where this duration is used except `Stats` and some formatters but it was the same in 2.4.0 and durations were accurate then. So there is some magic from which Intellij/AS is taking those duration but I'm lack of ideas currently.

**Comment by lsuski** [comment]
fixed by 2ed7777ed59d91bc6be256ba6b48f8bab6f869a0
