### ISSUE TITLE
Possible to run a single Scenario or Feature via IDE?

### ISSUE THREAD

**Issue by mtiidla** [cucumber/cucumber-android#30]
Is there any way to run a single Scenario or Feature from the IDE?

I have the[ Cucumber for Java Plugin](https://plugins.jetbrains.com/plugin/7212-cucumber-for-java) installed, which enables right clicking on a Scenario or Feature and run it:

![Screenshot 2019-10-11 at 15 04 55](https://user-images.githubusercontent.com/2339109/66653500-81b5a680-ec38-11e9-8cad-264fa2cb7e60.png)

But that will not include the instrumentation test runner for Android, so it will fail.

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.

**Comment by lsuski** [comment]
To run single scenario or any scenario group I want I have 2 classes:

This class is in .gitignore - it will be found by Cucumber only in my local machine an used for execution because it is before second class (A is before C :) )
```
@CucumberOptions(
		features = "features/my_feature.feature:10"
)
public class ATest extends CommonCucumberConfiguration
{
}
```

This class is in git and will be executed on CI
```
@CucumberOptions(
		features = "features"
)
public class CucumberConfiguration extends CommonCucumberConfiguration
{
}
```

**Comment by lsuski** [comment]
Yes, usually recompilation after editing this file i fast

**Comment by andreasmarkussen** [comment]
For future reference - An issue [cucumber-java plugin support for Android Instrumentation tests](https://youtrack.jetbrains.com/issue/IDEA-224658) has been created in the issue tracker of [Jetbrains Cucumber for Java Plugin](https://plugins.jetbrains.com/plugin/7212-cucumber-for-java)
