### ISSUE TITLE
Failed to read resource:file + filePath

### ISSUE THREAD

**Issue by dinhthaidaica** [cucumber/cucumber-android#35]
I'm trying to integrate Cucumber to my existing project with existing tests.

I keep following some tutorials from medium and your tutorial as well. I'm able to run the sample projects successfully but when I try to apply to my project, it keeps saying some error.

I tried to make some tricks but still doesn't work, if you guys can tell me what did I do wrong, so much appreciated. 

My setup:

**app.gradle**
```
defaultConfig {
        testInstrumentationRunner "cucumber.api.android.CucumberAndroidJUnitRunner"
    }
```

```
androidTest {
            java {
                srcDirs = ['tests/instrumentationTest']
                resources.srcDirs = ['tests/instrumentationTest/assets']
            }
            manifest.srcFile file('tests/instrumentationTest/AndroidManifest.xml')
        }
```

**My Feature file**

![image](https://user-images.githubusercontent.com/5735670/69439197-c0b23e00-0d46-11ea-936b-2f71a4a2e87a.png)

**Test Folder**

![image](https://user-images.githubusercontent.com/5735670/69438956-497caa00-0d46-11ea-98e5-47ed9eba23dd.png)

**Test Class**
![image](https://user-images.githubusercontent.com/5735670/69439081-8648a100-0d46-11ea-833e-ba2338e8d00f.png)

**The error log I have:**

![image](https://user-images.githubusercontent.com/5735670/69439486-5f3e9f00-0d47-11ea-80b3-2f85e1f37b6c.png)

**Then I changed the @CucumberOptions to**

![image](https://user-images.githubusercontent.com/5735670/69439561-8301e500-0d47-11ea-8083-0fe09539e9e2.png)

**And I got this **log:****
![image](https://user-images.githubusercontent.com/5735670/69439635-a62c9480-0d47-11ea-82ed-00f3a9b60f51.png)

I have tried so many ways for finding a workaround solution but no result at all. 
Any suggestion would be much appreciated.
Thank you.

**Comment by lsuski** [comment]
Your build.gradle looks strange, I've never had this androidTest section so probably it is wrong

**Comment by dinhthaidaica** [comment]
Thank you for your comment, but I don't think it's strange or is a problem.  I believe it is a very common setup for instrument test on Android. It runs well with only espresso (without cucumber)

Here is my full setup source set if you want to sneak peek.
<img width="671" alt="image" src="https://user-images.githubusercontent.com/5735670/69501779-81334f80-0f08-11ea-99f2-f38f6a7017de.png">

**Comment by lsuski** [comment]
It is strange because basically you overwrite default setup which for Android tests is src/androidTest/java and src/androidTest/assets. In my opinion in your configuration you don't setup assets dir but java resources dir which is different concept. That's why this file does not exists in runtime. You can debug if `context.getAssets().open` returns stream for this file

**Comment by dinhthaidaica** [comment]
well, you were right. My bad with assets folder for androidTest.
I have updated assets folder to 
`assets.srcDirs = ['tests/instrumentationTest/assets']` 

then I got the error 
`No tests found. This usually means that your test classes are not in the form that your test runner expects (e.g. don't inherit from TestCase or lack @Test annotations)` again.
![image](https://user-images.githubusercontent.com/5735670/69537526-9946b580-0f80-11ea-9736-dfacbe8a311f.png)

![Screen Shot 2019-11-25 at 12 43 37](https://user-images.githubusercontent.com/5735670/69537994-94363600-0f81-11ea-9407-e1951dcdaac7.png)


Do I miss anything else?

**Comment by lsuski** [comment]
Do you have any example in your scenario outline? Where are steps implementations?

**Comment by dinhthaidaica** [comment]
![image](https://user-images.githubusercontent.com/5735670/69551197-978aeb00-0f9c-11ea-953e-378647e68fe3.png)
Here is my folder construction. As my previous post said, I have no Example in my scenario outline, 
I changed to scenario but couldn't fix it

**Comment by lsuski** [comment]
As this is not standard android project structure the issue is propably caused by it. It is not issue with cucumber-android as cukeulator works. You can debug cucumber runner and see what exactly ia missing
