### ISSUE TITLE
Support for parallel cukes

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-android#4]
I've just merged https://github.com/cucumber/cucumber-jvm/pull/1389

However because android was removed while this PR was being developed, it did include some support for parallel cukes in Android. You can find that code here: 

https://github.com/cucumber/cucumber-jvm/tree/parallel-cukes-for-android

I would recommend copying android files and pasting them into this project. It will bring the android project up to date with cucumber-jvm.

**Comment by lsuski** [comment]
fixed by 2ed7777ed59d91bc6be256ba6b48f8bab6f869a0
