### ISSUE TITLE
Running both Cucumber tests and standard Junit tests

### ISSUE THREAD

**Issue by DenisBronx** [cucumber/cucumber-android#43]
I'm adding Cucumber to a module that already has instrumented tests (I have many modules and each of them has several instrumented tests). 
My problem is that when I use `CucumberAndroidJUnitRunner` I'm not able to run the existing instrumented tests (they are ignored) unless I switch back to the previous runner (in which case the cucumber tests are ignored).

Is this the expected behaviour or I'm doing something wrong? 
If this is the expected behaviour which workaround can I use?

**Comment by lsuski** [comment]
Check PR #39

**Comment by DenisBronx** [comment]
@lsuski thanks! this is what I was looking for

**Comment by Tabun24** [comment]
Have the same problem. It would be nice to have that PR in the release.

**Comment by lsuski** [comment]
Resolved in #39
