### ISSUE TITLE
Possible bug specifying multiple individual scenarios?

### ISSUE THREAD

**Issue by Elvis10ten** [cucumber/cucumber-android#44]
How can we specify individual test scenarios?

With the `AndroidJUnitRunner` you can specify multiple individual test cases using a comma with the `"class"` args, eg:

`"class=ClassName1#methodName1,ClassName2#methodName2"`

But the `CucumberRunner` only seems to support specifying only one scenario this way. Is this a bug?

I have a list of features and the scenarios I want to run, how do I specify that to the runner?

Using feature file line numbers won't work because the runner doesn't report the line numbers to `TestRunListener`. So we will have to somehow map the reported `className (featureName)` and `methodName (scenarioName)` back to the feature file number in other for third party tools we use to continue working.

**Comment by lsuski** [comment]
Why do you assume that cucumber runner does not support it? Sharding works well with cucumber and it is done exactly in this way. You can paste here your `@CucumberOptions` config and logcat output and I'll check if there areany misconfiguration

**Comment by Elvis10ten** [comment]
@lsuski , it wasn't only an assumption.

I first tried it and it didn't work (that is: multiple cases passed to the runner separated by a comma). No tests were run.

Then I looked into `CucumberJUnitRunner` from line 122 (attached the snippet below). It seems to only handle a single specified test case.

`
String testClassNameFromRunner = runnerArguments.getString(CucumberAndroidJUnitRunner.CUCUMBER_ANDROID_TEST_CLASS);
        String requestedFeatureName = null;
        String requestedScenarioName = null;
        if (testClassNameFromRunner != null) {
            String[] split = testClassNameFromRunner.split("#");
            if (split.length > 1) {
                requestedFeatureName = split[0];
                requestedScenarioName = split[1];
            } else {
                Log.e(TAG, "CucumberJUnitRunner: invalid argument '" + CucumberAndroidJUnitRunner.CUCUMBER_ANDROID_TEST_CLASS + "' = '" + testClassNameFromRunner + "'");
            }
        }
`

**Comment by lsuski** [comment]
Hmm, it looks like it is bug. However executing subset of scenarios in shard works but filtering is done in different layer. The code you've pasted is written speciffically for executing single scenario in single instrumentation run such as by android test orchestrator.

**Comment by lsuski** [comment]
As comma is allowed char for cucumber scenario/feature title it won't be easy to extract them from runner arg.

**Comment by Elvis10ten** [comment]
Thanks for the quick responses @lsuski .

My goal is to be able to dynamically specify multiple `featureName#scenarioName`.

Is there any other way I can achieve this?

On another note: Is there a restricted char in Cucumber? Maybe I can work on adding support for this use case.

**Comment by lsuski** [comment]
As generally running multiple scenarios is possible I would firstly debug how is it done currently with shard option. As I remember it is achieved by standard junit mechanism.
I'm not aware of any special char but be aware that titles can't have any char disallowed by file system

**Comment by lsuski** [comment]
To run multiple features you can specify `-e features=path/to/my/feature.feature:12,path/to/my/feature.feature:30` etc.
