### ISSUE TITLE
Support for java8 API?

### ISSUE THREAD

**Issue by davidvavra** [cucumber/cucumber-android#46]
Hi, is it possible to write java8-style step definitions with cucumber-android? It's helpful especially with Kotlin, it's almost like DSL. I tried to add java8 dependencies, but the build failed on not finding cucumber on classpath.

**Comment by lsuski** [comment]
Probably not but I've never tried. It also won't work on api without Java 8 classes (26 afaik).

**Comment by childnode** [comment]
have you tried to:
```
androidTestImplementation "io.cucumber:cucumber-android:4.4.1"
androidTestImplementation "io.cucumber:cucumber-java8:4.4.0"
```
where latter version was derived from https://github.com/cucumber/cucumber-android/blob/v4.4.1/build.gradle#L52

**Comment by jakob-grabner** [comment]
I would also like to use java8-style step definitions with cucumber-android. Unfortunately using  

`androidTestImplementation "io.cucumber:cucumber-android:4.4.1"
androidTestImplementation "io.cucumber:cucumber-java8:4.4.0"`

didn't work for me. The test started, but the test steps were not discovered.

**Comment by lsuski** [comment]
As AGP 4.0.0 is available we can upgrade cucumber-android to latest cucumber-java with java 8 and this should allow us to use java8-style step definitions. This requires some work which I plan to start in near future

**Comment by Foso** [comment]
Hi, are there any news on this? I only replaced cucumber-java with cucumber-java8 and was able to create java8 style steps in Java and Kotlin. Api 23 und 30 ran successful. But on Api 19 ist throwed: "io.cucumber.junit.UndefinedThrowable: The step "I should see "10.0" on the display" is undefined". You can see my diff here https://github.com/Foso/cucumber-android/commit/d32681b3c15af59472b1f86c48fee45581c1e879

**Comment by lsuski** [comment]
Error on api 19 could be not related with cucumber- java8. I don't usesuch low api and not sureif cucumber-android worked on it before

**Comment by Foso** [comment]
Okay, the min-sdk in my apps is 23, so everything works fine for me. I tried api 19 because i thought that this is the min-sdk for cucumber-android, because of the readme.

> NOTE: Although minSdkVersion for 'cucumber-android' is 14 it requires Java 7 language features and minimum Android API level 19. This is done purposely to allow using cucumber in apps with lower minSdk (to avoid compile errors) but tests should be run on devices with API >= 19

Please try adding the java8 dependency. It would be great to have the option to write steps in java8 style.

**Comment by lsuski** [comment]
Right now java8 style is not supported, use Kotlin instead
