### ISSUE TITLE
Calling from Untrusted UID Error

### ISSUE THREAD

**Issue by badrinrs** [cucumber/cucumber-android#47]
I am using ```
androidTestImplementation 'com.squareup.spoon:spoon-client:1.7.1'

    androidTestImplementation 'androidx.test.uiautomator:uiautomator:2.2.0'

    androidTestImplementation 'io.cucumber:cucumber-android:4.4.1'
    androidTestImplementation 'io.cucumber:cucumber-picocontainer:4.4.0'

Even with those packages, I am getting 

```
06-04 22:28:41.023   915  2699 W ActivityManager: Crash of app <Package> running instrumentation ComponentInfo{<Package>.test/<Package>.test.cucumber.runner.CucumberTestRunner}
06-04 22:28:41.026  5097  7077 W Binder  : Binder call failed.
06-04 22:28:41.026  5097  7077 W Binder  : java.lang.SecurityException: Calling from not trusted UID!
06-04 22:28:41.026  5097  7077 W Binder  : 	at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:468)
06-04 22:28:41.026  5097  7077 W Binder  : 	at android.app.UiAutomationConnection.shutdown(UiAutomationConnection.java:372)
06-04 22:28:41.026  5097  7077 W Binder  : 	at android.app.IUiAutomationConnection$Stub.onTransact(IUiAutomationConnection.java:222)
06-04 22:28:41.026  5097  7077 W Binder  : 	at android.os.Binder.execTransact(Binder.java:731)

**Comment by lsuski** [comment]
Ok but how is it related with cucumber?

**Comment by badrinrs** [comment]
I am not sure... I wanted more information on how this can fixed in my instrumentation tests

**Comment by badrinrs** [comment]
This seems to be an issue on only 1 device so far. On All other devices, tests seem to be working as expected.

**Comment by badrinrs** [comment]
Thanks! The issue is fixed. Just removed JSON configuration for Android 6 and below helped fix it.
