### ISSUE TITLE
[Question] How to run individual lines of scenario examples

### ISSUE THREAD

**Issue by efemoney** [cucumber/cucumber-android#55]
Is it possible to specify the exact lines of the examples to run and how can we do that with cucumber Android?

**Comment by lsuski** [comment]
run tests with `features = "features/my_feature.feature:123"` where 123 is line of example

**Comment by malikmudassarhussain** [comment]
How to specify line number when we have more than one scenario in one feature and running all features files together?

**Comment by lsuski** [comment]
If you run all scenarios you can't run just only one. `features = "features/my_feature.feature:123"` runs single scenario/example/scenario outline which starts at line 123. It doesn't matter if there are many scenarios in this feature file
