### ISSUE TITLE
Running tests on robolectric and actual device

### ISSUE THREAD

**Issue by AbdElraoufSabri** [cucumber/cucumber-android#58]
Hello, Thanks for the great library. Yet I have a question.

Now we can run android tests using robolectric on JVM, Can I run cucumber tests using robolectric?

I have the following structure: `build.gradle.kts`
```kotlin
sourceSets.all {
    java.srcDirs("src/$name/kotlin")
    when (name) {
        "test", "androidTest" -> {
            java.srcDirs("src/sharedTest/kotlin")
            assets.srcDirs("src/sharedTest/assets")
        }
    }
}
```

So I've **sharedTest** folder available to `jvm` and `androidTest`. Evantually, I'll put cucumber feature files in `src/sharedTest/assets/features` and step defs inside `src/sharedTest/kotlin`. As those will be shared between both `jvm` and `androidTest`.

**My question how to run tests on both robolectric and actual device?**

**Comment by lsuski** [comment]
Cucumber-android is dedicated for tests on real device. For junit tests on jdk you can use cucumber-junit. However it has its own runner Cucumber so you can't use it alongside Robolectric runner.

**Comment by lsuski** [comment]
You would have to build new runner on top of Robolectric one with functionality of Cucumber

**Comment by AbdElraoufSabri** [comment]
Thanks for pointing me in the right direction.
