### ISSUE TITLE
Add dependency description in README

### ISSUE THREAD

**Issue by aygalinc** [cucumber/cucumber-android#6]
Maybe a section in README file where dependency management of cucumber-android 
(just a line:
 // Use the stable Cucumber android version in androidTest
androidTestImplementation 'io.cucumber:cucumber-android:3.0.2') is described
would be nice in order to avoid confusion with older info.cukes:cucumber-android dependency.

**Comment by aslakhellesoy** [comment]
Could you please send a PR with the proposed change?
