### ISSUE TITLE
Cucumber does 't work in project when it is defined applicationIdSuffix

### ISSUE THREAD

**Issue by fllaryora** [cucumber/cucumber-android#63]
Hi, Good morning.
I am not cucumber expert.
When my project use cucumber along with build variants + applicationIdSuffix  It run into troubles like:
 

> io.cucumber.junit.CucumberJUnitRunnerBuilder > initializationError[Mi A2 - 10] FAILED
>         cucumber.runtime.CucumberException: No CucumberOptions annotation
>         at io.cucumber.junit.AndroidJunitRuntimeOptionsFactory.createRuntimeOptions(AndroidJunitRuntimeOptionsFactory.java:55)

Does somebody knows how can I configure a  cucumber's project  along with build variants + applicationIdSuffix ?

Thanks in advance.

**Comment by lsuski** [comment]
You need to provide class annotated with `CucumberOptions` in test application package. By default this is `applicationId`.`test`. If you are using  applicationIdSuffix then I suggest to either define in build.gradle `android.defaultConfig.testApplicationId = your_package.test` and provide class in package your_package_test or provide such class for each variant package

**Comment by fllaryora** [comment]
Thank you @lsuski for your time!

After Add testApplicationId in build.gradle It throw me

> Build file '/Users/xxxxxxxx/app/build.gradle' line: 8
>
> A problem occurred evaluating project ':app'.
> > No signature of method: build_y7f27fqlvljy0wpva7yt9ojc.android() is applicable for argument types: (build_y7f27fqlvljy0wpva7yt9ojc$_run_closure1) values: [build_y7f27fqlvljy0wpva7yt9ojc$_run_closure1@1ef017d5]

Do you have any clue?
Now I'm working on it.

**Comment by leanlg3** [comment]
I've the same problem. Any idea guys?

**Comment by lsuski** [comment]
I have this and it works in my project
```
android {

    defaultConfig {
        applicationId "com.example"
        versionCode 1
        versionName "1

        testApplicationId "com.example.test"
        testInstrumentationRunner 'io.cucumber.android.runner.CucumberAndroidJUnitRunner'

    }

    flavorDimensions "flavs"
    productFlavors {
        flav1 {
            dimension "flavs"
            applicationIdSuffix ".flav1"
        }
        flav2 {
            dimension "flavs"
            applicationIdSuffix ".flav2"
        }
    }
```

and class in `src/androidTest/java` (or `src/androidTest/kotlin`)
```
package com.example.test

import io.cucumber.junit.CucumberOptions

@CucumberOptions(features = ["features"])
class CucumberConfiguration
```

**Comment by fllaryora** [comment]
Finally after hard work It run the first test!

The clue about testApplicationId is pointing to the package of the definition of CucumberOptions annotation, in Addition with the hint  regarding testInstrumentationRunner as well as testApplicationId is not affected with the suffix were useful to me.

So after read the readme n-times as well your coments.
I made a useful check list:
-  The features are in: /app/src/androidTest/assets/features
- The first parameter of testInstrumentationRunner from gstring to string
- The first parameter of testApplicationId from gstring to string
- The  testInstrumentationRunner is pointing to the runner class ignoring the suffix.
- The  testApplicationId is pointing to the CucumberOptions definition ignoring the suffix.
- The glue parameter  ignore the suffix too.

Thank you @lsuski !
