### ISSUE TITLE
Is there a way to continue to next scenario when there is a crash

### ISSUE THREAD

**Issue by badrinrs** [cucumber/cucumber-android#67]
Is there a way to continue to next scenario when there is a crash. An example, I see the following error and the next few tests do not run after the process has crashed. Is there a way to work around the crash
```
INSTRUMENTATION_RESULT: shortMsg=Process crashed.
INSTRUMENTATION_CODE: 0
```

**Comment by lsuski** [comment]
I don't think that this is possible in instrumentation tests at all because this requires starting instrumentation process again and can be done only by adb. It is not scope of cucumber-android
