### ISSUE TITLE
Run different suites

### ISSUE THREAD

**Issue by VikOles** [cucumber/cucumber-android#69]
Hello. I want to have a few test's suites (Regression, smoke, etc) Also our application has several flavours and buildTypes.
Is it possible to setup cucumber for this purpose with this type of application?

**Comment by lsuski** [comment]
Cucumber-android requires that class annotated with @CucumberOptions resides in testApplicationId package. This annotation lets you define which scenarios and/or features should be executed. One option is to have multiple such classes with proper @CucumberOptions configuration which filters scenarios based on tags or feature path and place this classes in corresponding buildType src/androidTest packages

**Comment by VikOles** [comment]
@lsuski  So you mean I can have several classes with @CucumberOptions in one package?

**Comment by lsuski** [comment]
Not in final test apk. 
They can be in the same package but in different source roots or in different packages but those packages must be testApplicationId - you can have different for different flavours

**Comment by lsuski** [comment]
No, you can have only one class with this annotation in testApplicationId package. You can have have only one testApplicationId package for flavour.

I think that you can pass arguments for instrumentation which then will be merged with this annotation configuration. For arguments reference check cucumber cli docs

**Comment by VikOles** [comment]
@lsuski  Could you share the documentation for it? Because I can't find information about cucumber-android in cucumber docs. Also, I forgot to mention that I use an orchestrator.

**Comment by lsuski** [comment]
Check this https://cucumber.io/docs/cucumber/api/

**Comment by lsuski** [comment]
To define different classes with different `CucumberOptions` annotations you can use `optionsAnnotationPackage` instrumentation arg
