### ISSUE TITLE
Unable to create instrumentation test configuration

### ISSUE THREAD

**Issue by pueffl** [cucumber/cucumber-android#70]
Hello!

As far as I can see it is no longer possible to create an instrumentation test configuration. I am not able to create one in my application, so I tried to do the same in cucumber-android. The provided configuration works, but there seems to be no way to create the same configuration from scratch: Only 'android.test.InstrumentationTestRunner' is available and no selection of another Runner is possible (button is disabled). 
Might be an AS problem, but I put it here first, maybe I miss something.

**Comment by lsuski** [comment]
I am not aware of any such issue, rather AS problem.

**Comment by pueffl** [comment]
Ok, so you are able to create a new intrumentation test configuration from scratch? If so, just close the ticket, I will open another for AS.
