### ISSUE TITLE
Report not generated 

### ISSUE THREAD

**Issue by pratham7674** [cucumber/cucumber-android#71]
as mentioned in readme Used 
`"format = {"junit:/data/data/com.mytest/JUnitReport.xml", "json:/data/data/com.mytest/JSONReport.json"}" `also tried 
`plugin = {"junit:/data/data/com.mytest/JUnitReport.xml", "json:/data/data/com.mytest/JSONReport.json"}`

none of these generated reports, can you please elaborate more on generating reports?

**Comment by lsuski** [comment]
If you start tests with gradle task then app is uninstalled after tests so any files created during tests will be removed also. Gradle task provides its own test reports, you can also use spoon for tests execution or change paths here to something independent of the app (but there will be permission to write external storage required)

**Comment by pratham7674** [comment]
> If you start tests with gradle task then app is uninstalled after tests so any files created during tests will be removed also. Gradle task provides its own test reports, you can also use spoon for tests execution or change paths here to something independent of the app (but there will be permission to write external storage required)


Thanks for the quick response @lsuski . request you to help with detailed documentation regarding developing native cucumber reports using `CucumberOptions plugin option` because they are not generated in my local machine

**Comment by lsuski** [comment]
Right now standard `cucumber-jvm` plugins like `html` and `junit` are not supported because they use api not available on Android
