### ISSUE TITLE
Features not recognizing Steps with glue option when running gradle test

### ISSUE THREAD

**Issue by gabrielglbh** [cucumber/cucumber-android#72]
I have performed all steps carefully for setting up my android project in order to use cucumber to perform some unit tests in my app.

My app module `build.gradle` has the following dependencies:

    testImplementation 'junit:junit:4.13.2' 

    testImplementation "io.cucumber:cucumber-java:6.10.2"
    testImplementation "io.cucumber:cucumber-junit:6.10.2"
    testImplementation "io.cucumber:cucumber-android:4.8.3"

And the `testInstrumentatorRunner` is set to my custom runner class which is `com.my.android.app.RunCucumberTest`:

    @RunWith(Cucumber::class)
    @CucumberOptions(
        features = ["src/test/assets/features"],
        glue = ["com.my.android.app"],
        plugin = ["pretty"]
    )
    class RunCucumberTest : CucumberAndroidJUnitRunner()

I define my Scenarios under `src/test/assets/features`: 

    Feature: Create User

    Scenario Outline: Criteria 1
      Given the user that enters its username "<name>"
      When the user validates its username
      Then the username length must be less or equal than 32
      Examples:
        | name    |
        | Gabriel |

And my steps under `src/test` included in the package `com.my.android.app`:

    class CreateGroupSteps {
        private lateinit var groupName: String
        private var validGroupName = true
        init {
            @Given("the user that enters its group name {string}")
            fun user_enters_group_name (groupName: String) {
                this.groupName = groupName
            }
            @When("the user validates its group name")
            fun user_validates_group_name () {
                validGroupName = groupName.matches(Regex(GROUP_NAME_VALIDATOR))
            }
            @Then("the group name length must be less or equal than 32")
            fun group_name_length_less_or_equal_than_32 () {
                assertTrue(groupName.length <= 32 && validGroupName)
            }
        }
    }

Now, something strange happens: either when I run in the console `gradle test` or when I am in the `RunCucumberTest` class and I run it, all Scenarios are present and recognized but they end in failure because the Steps are not defined. Basically throwing a `io.cucumber.junit.UndefinedStepException`.

I thought that there was something wrong with the `glue` option in the `@CucumberOptions`. So I change it and run the task again: same result. I even removed the parameter and again, the same result.

It seems the `glue` option is completely ignored when running the `gradle test` task and therefore the Steps are not being recognized.

**Comment by douglasciole** [comment]
I'm getting the same issue.

**Comment by lsuski** [comment]
```

testImplementation "io.cucumber:cucumber-java:6.10.2"
testImplementation "io.cucumber:cucumber-junit:6.10.2"
testImplementation "io.cucumber:cucumber-android:4.8.3"
```
cucumber-android is for android insstrumented test not unit tests - for unit tests you can use just
```

testImplementation "io.cucumber:cucumber-java:6.10.2"
testImplementation "io.cucumber:cucumber-junit:6.10.2"
```
