### ISSUE TITLE
Skip Steps Based on Condition

### ISSUE THREAD

**Issue by anas-baadshah** [cucumber/cucumber-android#73]
Do we have any mechanism to skip a test in the middle of execution based on some conditions?
For example,
```
@myTest
  Scenario Outline: Sample scenerio
    Given I am on main screen
    When I select visible buttin
    And I select white screen
    And skip if the condition met
    And continue with the black board
    And force to go to next screen
```

Here on step `skip if the condition met` can I skip the test and make the scenario passed with a reason? 
`Assume` in JUnit is an option but it's not working with Cucumber-android, Any helps??

**Comment by lsuski** [comment]
I throw AssumptionViolatedException in  @Before hooks to skip scenarios which should not be executed because of specific device conditions. Maybe it would work when thrown on step also

**Comment by anas-baadshah** [comment]
Thanks, @lsuski, yes I tried, and it's working fine. 
`Assume.assumeFalse("Message", true)`
