### ISSUE TITLE
Customizing CucumberOptions Annotation Location

### ISSUE THREAD

**Issue by cody1024d** [cucumber/cucumber-android#74]
Let me start off by thanking ya'll for maintaining this!

I think I've found a use-case that the current solution cannot handle, but perhaps I have missed it.

I am creating an internal Framework that wraps around cucumber-android to provide to our developers to allow them to write BDT tests. Because of this, I was hoping to encompass the CucumberOptions annotation within the framework, to enforce particular directories/conventions to ensure consistency across our multiple libraries.

As of right now, I don't believe this is possible, because the CucumberJUnitRunner looks for classes only within the context package, which in my above case would not work.

Is there any other way to provide the location of the CucumberOptions to the framework? I believe I could probably write a custom `CucumberAndroidJUnitRunner` which then provides a custom `CucumberJUnitRunnerBuilder` but I'd rather avoid duplicating a lot of this boilerplate for one small extension.

Thanks,
Cody

**Comment by lsuski** [comment]
Could you be more precise on what exactly you want to enforce and what do you mean by `CucumberJUnitRunner looks for classes only within the context package`?
In fact CucumberJUnitRunner looks for first class annotated with `@CucumberOptions` only within the test context package but other classes like steps implementations and hooks can be in different packages

**Comment by cody1024d** [comment]
Hey @lsuski 

Absolutely, I'll provide more details!

I'd like to enforce the location that glue-files can be placed, as well as the feature files. Further, I'd honestly just like to abstract out the Cucumber configuration (through the annotation) because it will be in the hands of some more junior developers and would be a potential "push-back" on them adopting BDD.

> Could you be more precise on what exactly you want to enforce and what do you mean by CucumberJUnitRunner looks for classes only within the context package?

What I meant by this, is inside the class `AndroidJunitRuntimeOptionsFactory` it specifically looks only at classes within the test context package. What I would like to see, if possible, is the ability to customize the package it looks in.

Here's my exact use-case:

Say I'm creating a framework named `com.foo.BDD`.  It's going to be used across many different frameworks, such as `com.foo.A` and `com.foo.B`.  Because of this, I'd like to put the `CucumberOptions` annotation on a class within my `com.foo.BDD` framework that will be imported as an androidTest dependency.  Currently it's not able to be found by the `AndroidJunitRuntimeOptionsFactory` because of the above implementation

**Comment by lsuski** [comment]
You can achieve it somehow by inheritance, I think I do similar things in my company. `@CucumberOptions` is merged from all classes through inheritance path. So you can have class annotated in package `com.foo.BDD ` with whatever configuration you want and also annotated classes in other packages you mentioned - those classes should inherit from this from package  `com.foo.BDD`. Last annotated class has to be in test context package of course but annotation can be empty - all configuration about feature files glues etc. will be inherited.

**Comment by cody1024d** [comment]
Ah that is a good point, I could do that.  If you would believe it though, even *that* I'm worried about lol. I'm at a shop where I'd rather this framework I'm working on *do as much as possible*, if I can.

I can already imagine myself getting **so** many emails asking why the tests are saying that no CucumberOptions annotation exists lol.

I think barring any other ideas, I'm going to go the route of customizing the runner classes I need...it's crazy, but I need to be THAT thorough XD

**Comment by lsuski** [comment]
Ok, as you wish, but maybe your change could be part of official repository depending on what you will change

**Comment by cody1024d** [comment]
@lsuski 

I've created the PR that will help me with my use-case.  It's pretty un-invasive, and just adds the ability for someone to define the package location via an InstrumentationRunnerArgument
