### ISSUE TITLE
Not able to run features under Android Studio

### ISSUE THREAD

**Issue by oradkovskyy-hungerstation** [cucumber/cucumber-android#78]
With cloned unmodified repo, I'm not able to run tests using the UI (for example, by right clicking calculate.feature and clicking "Run Feature: calculate') - I'm getting "Undefined scenarios". My run/debug config looks like this:
![image](https://user-images.githubusercontent.com/70510642/122031861-c31c3300-cdd7-11eb-88c8-e7f1f3bd6d79.png)

Studio version: 4.2.1 build AI-202.7660.*
cucumber-java plugin version: cucumber-java-202.6397.59 (had to install manually, version from marketplace does not work, likely is not compatible with AS)

Answer to possible question re glue: when I just use package, Im always getting `No instrumentation registered! Must run under a registering instrumentation.`

**Comment by lsuski** [comment]
You are running features using CLI (which is used by Cucumber For Java Intellij Plugin) - this is Android instrumented test - you can only run it using Android Instrumented Test Run configuration

**Comment by oradkovskyy-hungerstation** [comment]
Thank you. Just for the record, I understood the above answer as "cucumber features can only run using command line"
