### ISSUE TITLE
Run only one scenario easily from Android Studio ?

### ISSUE THREAD

**Issue by michgauz** [cucumber/cucumber-android#79]
Hello !
Is it possible to run only one specific scenario from Android Studio, without tricks (add a tag for example for the one we wanna test), and without the command line interface ?
I have only the right click option  on the androidTest/java folder, then "Run tests", working, but it performs all the tests.

Thanks for your time

**Comment by lsuski** [comment]
Assuming that you have such class :
```
@CucumberOptions(features = ["features"],glue = ["com.sample"])
class CucumberConfiguration
```
you can change it to
```
@CucumberOptions(features = ["features/my_feature.feature:35"],glue = ["com.sample"])
class CucumberConfiguration
```
where 35 is line at which desired scenario starts or example row line of scenario outline
