### ISSUE TITLE
java.lang.NoClassDefFoundError: org/w3c/dom/ElementTraversal

### ISSUE THREAD

**Issue by JooperGe** [cucumber/cucumber-android#86]
I'm getting this error by running './gradlew assemble', 
_Execution failed for task ':cucumber-android:mergeDebugJniLibFolders'.
'> org/w3c/dom/ElementTraversal_

**Comment by lsuski** [comment]
It looks like JDK version issue. What JDK are you using? Maybe it is not compatible with this version of AGP
