### ISSUE TITLE
Support for Jetpack Compose

### ISSUE THREAD

**Issue by lburcon** [cucumber/cucumber-android#87]
**Describe the bug**
When working with Compose and using AndroidComposeTestRule (or just ComposeTestRule), application is not being started at all when using CucumberAndroidJUnitRunner - looks like the rule is not being initiated.
Everything works fine when using ActivityTestRule to start cucumber tests with CucumberAndroidJUnitRunner, but to make it work with Jetpack Comose I had to do plenty of tweaks in a local copy of compose-ui-testing library.

**To Reproduce**
Create a simple test using `createAndroidComposeRule<MainActivity>()` and try launching Cucumber tests. Activity is not being started.

**Expected behavior**
CucumberAndroidJUnitRunner should initialize the application and start tests. 

**Smartphone (please complete the following information):**
Any device

**Comment by lsuski** [comment]
Probably `CucumberAndroidJUnitRunner` does not work well with junit rules. I have plan to add support for compose in few months. Currently is hard to say for me what exactly will be needed.

**Comment by lsuski** [comment]
I've started working on this and support for junit rules should be available soon, I hope in 1-2 weeks if nothing unexpected happens.

**Comment by lsuski** [comment]
Will be available in `4.9.0`

**Comment by mochadwi** [comment]
Finally!
