### ISSUE TITLE
V4.9.0 snapshot not available in maven

### ISSUE THREAD

**Issue by duenes25** [cucumber/cucumber-android#91]
Hello, 
I am having an issue with using this library with Jetpack Compose.  I see there is a v4.9.0 snapshot version that will likely fix the issue I am having, however I cannot find this version in Maven.  Is there a reason this version is not yet published to maven?

Thank You

**Comment by mpkorstanje** [comment]
Publishing automatically requires credentials to be stored where an automated system. Until recently GitHub had no way to limit access to these credentials to a trusted group of contributors.

Additionally this project is mostly developed and maintained by volunteers in their spare time. As such I imagine that publishing snapshots is not a priority.

If anything you should be able to fork the project and upload a snapshot to your own artifact repository.

**Comment by duenes25** [comment]
@mpkorstanje Thanks for the information. Are there instructions for publishing?  Is there a way to also publish locally?

**Comment by mpkorstanje** [comment]
Have a look at `build.gradle` and the gradle docs:

https://docs.gradle.org/current/userguide/publishing_maven.html
https://github.com/gradle-nexus/publish-plugin

**Comment by lsuski** [comment]
It is available here https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-android/4.9.0-SNAPSHOT/

You have to add sonatype snapshot repository to build.gradle.

I will release closed version soon (hopefully 1 week)

**Comment by mpkorstanje** [comment]
Ah. Cool. Are you deploying these manually?

**Comment by lsuski** [comment]
No, I've setup github release. https://github.com/cucumber/cucumber-android/blob/main/RELEASING.md.

**Comment by mpkorstanje** [comment]
Ah. That's effectively manual because you have to create the branch.

**Comment by lsuski** [comment]
Yes, sure but you always have to do something, e.g. change version number :)

**Comment by duenes25** [comment]
> It is available here https://oss.sonatype.org/content/repositories/snapshots/io/cucumber/cucumber-android/4.9.0-SNAPSHOT/
> 
> You have to add sonatype snapshot repository to build.gradle.
> 
> I will release closed version soon (hopefully 1 week)

Thank you I will take a look at sonatype.

**Comment by lsuski** [comment]
@duenes25 4.9.0 should be now available in Maven Central https://search.maven.org/artifact/io.cucumber/cucumber-android/4.9.0/aar
