### ISSUE TITLE
BeforeAll and AfterAll for Android

### ISSUE THREAD

**Issue by matthanmethane** [cucumber/cucumber-android#98]
Hey,

First of all, thank you for making and maintaining such amazing framework. It is helping adopt BDD to my company's SW a lot.

I was wondering if cucumber-android supports BeforeAll and AfterAll. I have seen examples from cucumber-jvm() [Link](https://github.com/cucumber/cucumber-jvm/tree/main/java#hooks) however, the version of cucumber-java in android seem to not support this. Are there any plan to include this or if anyone knows any ways to work around it please lmk! 

Thank you so much!

**Comment by lsuski** [comment]
It is probably part of newer cucumber-jvm which is not compatible with cucumber-android. You can probably achive something similar by overriding CucumberAndroidJUnitRunner.onStart and CucumberAndroidJUnitRunner.finish

**Comment by matthanmethane** [comment]
Hey, that's awesome. Thanks!
